parameters:
#    adminuser.example.class: Admin\userBundle\Example

services:
#    adminuser.example:
#        class: %adminuser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
